/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rarediscovery.widgets;

import com.rarediscovery.services.logic.Functions;
import java.awt.Dimension;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author usaa_developer
 */
public class WorksheetPanel extends javax.swing.JPanel {

    private TableModel model_Table;
    private JPanel parentContainer;
    
    private String[] columnNames = new String[21];
    private Dimension VIEW_PORT_SIZE = new Dimension(800, 600);
    
    /**
     * Creates new form WorksheetPanel
     */
    public WorksheetPanel(final JPanel pc) 
    {
        initComponents();
        
        int width = 1000;
        if (pc != null)
        {
            this.parentContainer = pc;
            width = parentContainer.getWidth();
        }
            
        // Create A-Z table & empty columns
        
        for(int i=1;i<=20;i++)
        {
             columnNames[i] = ""+i;
        }
        
        // Initialize the models
        model_Table = new DefaultTableModel(columnNames, 20);
                 
        //Wire the ui to the model
        ui_Worksheet.setModel(model_Table);
           
        // Create Grid
//        String[][] grid = new String[20][26];
//        for(int row=0;row < grid.length;row++)
//        {
//          grid[row] = emptyDataRow;
//        }
        
        
    }

    public void loadData(final String[][] dataGrid)
    {
       model_Table= new DefaultTableModel(dataGrid, columnNames);
       ui_Worksheet.setColumnSelectionAllowed(true);
      
       //Wire the ui to the model
       ui_Worksheet.setModel(model_Table);
           
       Functions.log("Display data");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ui_Worksheet = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Preview", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N
        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 560));

        ui_Worksheet.setAutoCreateRowSorter(true);
        ui_Worksheet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ui_Worksheet.setColumnSelectionAllowed(true);
        ui_Worksheet.setPreferredSize(new java.awt.Dimension(300, 500));
        jScrollPane1.setViewportView(ui_Worksheet);

        add(jScrollPane1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ui_Worksheet;
    // End of variables declaration//GEN-END:variables
}
